"""Render docs/INVENTORY.md from docs/inventory-baseline.json.

The redesign spec's §1 is a hand-written feature list, and a hand-written
list is exactly the thing that goes stale while everyone believes it. This
generates the same document from what the browser actually rendered, so the
contract and the site cannot disagree.

    python3 tools/inventory_doc.py
"""
import collections
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.join(ROOT, "docs", "inventory-baseline.json")
OUT = os.path.join(ROOT, "docs", "INVENTORY.md")

TITLES = {
    "recommended": "Recommended", "live": "Live", "edge": "Edge Board",
    "scanner": "Scanner / Market Scanner", "longshots": "Long Shots",
    "trending": "Trending", "players": "Players", "rosters": "Rosters",
    "standings": "Standings", "record": "Record",
    "intel": "Polymarket / Informed Flow", "fantasy": "Fantasy",
    "ufc": "UFC", "why": "Reference (why)", "about": "About",
    "game": "Game board (no nav tab — reached from a venue card)",
}


def main():
    inv = json.load(open(BASE, encoding="utf-8"))
    pages, views, sports = inv["pages"], inv["views"], inv["sports"]

    cls = collections.defaultdict(set)
    prose = collections.defaultdict(set)
    aff = collections.defaultdict(lambda: collections.defaultdict(set))
    seen_in = collections.defaultdict(set)
    for key, val in pages.items():
        _w, sport, view = key.split("|")
        cls[view] |= set(val["classes"])
        prose[view] |= {s for s in val["strings"] if len(s) > 70}
        for a in ("buttons", "expanders", "inputs", "links"):
            aff[view][a] |= set(val[a])
        if val["strings"]:
            seen_in[view].add(sport)

    global_cls = set.intersection(*[cls[v] for v in views if cls[v]])

    L = []
    w = L.append
    w("# Feature inventory — generated, do not hand-edit\n")
    w("Generated by `tools/inventory_doc.py` from `docs/inventory-baseline.json`,")
    w("which `tools/inventory.mjs` harvests by rendering every view of every")
    w("sport in a real browser at 1280px and 390px.\n")
    w("This is the machine-checkable half of the redesign spec's §1")
    w("preservation contract. The prose contract says what must survive; this")
    w("says what is actually there, and `node tools/inventory.mjs --diff")
    w("docs/inventory-baseline.json` says whether it still is.\n")
    w(f"**{len(pages)} pages · "
      f"{len(set().union(*[set(p['strings']) for p in pages.values()]))} distinct strings · "
      f"{len(set().union(*[set(p['classes']) for p in pages.values()]))} classes · "
      f"{len(views)} views × {len(sports)} sports × 2 widths**\n")
    w("---\n")
    w("## Views\n")
    w("| View | Sports | Components | Explanatory prose | Expanders | Inputs |")
    w("|---|---|---|---|---|---|")
    for v in views:
        w(f"| {TITLES.get(v, v)} | {len(seen_in[v])}/{len(sports)} | "
          f"{len(cls[v] - global_cls)} | {len(prose[v])} | "
          f"{len(aff[v]['expanders'])} | {len(aff[v]['inputs'])} |")
    w("")
    w("---\n")
    for v in views:
        w(f"## {TITLES.get(v, v)}  `#{v}`\n")
        own = sorted(cls[v] - global_cls)
        if own:
            w("**Components** (CSS classes unique to this view — each is a")
            w("thing on screen that has to still be a thing on screen):\n")
            w("```\n" + "\n".join(
                "  ".join(own[i:i + 6]) for i in range(0, len(own), 6)) + "\n```\n")
        for a, label in (("expanders", "Expanders"), ("inputs", "Inputs"),
                         ("links", "Links")):
            items = sorted(x for x in aff[v][a] if x)
            if items:
                w(f"**{label}:** " + " · ".join(f"`{i}`" for i in items[:12]) + "\n")
        if prose[v]:
            w(f"**Explanatory prose — {len(prose[v])} passage(s), must survive")
            w("verbatim:**\n")
            for s in sorted(prose[v])[:40]:
                w(f"- {s}")
            w("")
        w("---\n")

    open(OUT, "w", encoding="utf-8").write("\n".join(L))
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
